# -------------------------------- Fishes --------------------------------
# source =>
SOURCE_FISHES_HOST = "localhost"
SOURCE_FISHES_USERNAME = ""
SOURCE_FISHES_PASSWORD = ""
SOURCE_FISHES_DATABASE = "CBI_Arzi"
SOURCE_FISHES_SCHEMA = "LTS"
SOURCE_FISHES_TABLE = "FISHES"
SOURCE_FISHES_PK = "fish_id"

# target =>
TARGET_FISHES_HOST = ""
TARGET_FISHES_USERNAME = ""
TARGET_FISHES_PASSWORD = ""
TARGET_FISHES_DATABASE = ""
TARGET_FISHES_SCHEMA = ""
TARGET_FISHES_TABLE = ""
TARGET_FISHES_PK = "fish_id"
